
# The unique identifier of the application.
name: wordpress
# The language that will run your application.
type: php:5.6
# The way to build your application.
build:
    flavor: composer
# The way services are mapped within your application.
relationships:
    database: "mysql:mysql"

# The way your application is exposed to the web.
web:
    locations:
        "/":
            expires: -1
            passthru: "/index.php"
            index:
                - index.php
            allow: true
# The size of the persistent disk size of your application in MB.
disk: 2048
# The volumes that are mounted under a writable shared resource.
mounts:
    "/tmp": "shared:files/tmp"
    "/private": "shared:files/private"
# The shell commands to run during the build or deployment process.
hooks:
    # We run deploy hook after your application has been deployed and started.

# The processes that are triggered on a schedule.
